### ISSUE TITLE
Lane points mixing issue

### ISSUE THREAD

**Issue by GrayFur** [cardwing/Codes-for-Lane-Detection#109]
I'm testing your implementation on a sequence with more than 4 lanes. As a result got some frames where the detection is pretty good, but also lots of situations where the lane points are mixed. As an example I attached four prob maps and the frame itself. The prob maps of some lines contain lots of points from a completely different line.  Is there any way to reduce the number of false detections for each separate line? 

![example_022](https://user-images.githubusercontent.com/24624290/59356003-3ce53600-8d52-11e9-92e2-ffe547f0a758.jpg)
![example_021_1_avg](https://user-images.githubusercontent.com/24624290/59355992-3b1b7280-8d52-11e9-8fda-999c0d9c7f10.png)
![example_021_2_avg](https://user-images.githubusercontent.com/24624290/59355997-3bb40900-8d52-11e9-8a98-f98306a9c10a.png)
![example_021_3_avg](https://user-images.githubusercontent.com/24624290/59355999-3c4c9f80-8d52-11e9-8c15-2e5506c3bebe.png)
![example_021_4_avg](https://user-images.githubusercontent.com/24624290/59356000-3c4c9f80-8d52-11e9-8cd4-9a263fcd8874.png)

**Comment by cardwing** [comment]
This image looks quite normal and the trained model should perform well if given enough training data of this driving scenario. However, since you just test the generalization ability of our trained model on a different dataset, unsatisfactory results are normal. You may try some transfer learning methods like adversarial learning to bridge the gap between datasets or try some post-processing methods like using rule-based unnormal lane point removing or adaptively set the probability threshold to select correct lane points.
