### ISSUE TITLE
What are sum and power used for in predicting probability maps and where to compute loss?

### ISSUE THREAD

**Issue by heethesh** [cardwing/Codes-for-Lane-Detection#115]
**Network: ENet-Label**
If I'm not wrong you are feeding outputs from stage 2 and 3 of ENet encoders to the following sequentials each of input dimensions (1, 128, 36, 100) for an input image of (1, 3, 288, 800). 

```
seq_2:add(nn.Power(2))
seq_2:add(nn.Sum(1, 3))
seq_2:add(nn.SpatialUpSamplingBilinear(8))
seq_2:add(nn.SpatialSoftMax())

seq_3:add(nn.Power(2))
seq_3:add(nn.Sum(1, 3))
seq_3:add(nn.SpatialUpSamplingBilinear(8))
seq_3:add(nn.SpatialSoftMax())
```

Why are feature map elements raised to power 2? How do you reduce the feature channels from 128 to n-lane maps? Also I see that `seq_2` and `seq_3` are concatenated later. How do you compute the loss against ground truth lane map? It is hard to understand this from the code.

**Comment by cardwing** [comment]
The power operation is used to enlarge the difference between elements of the whole feature map. The sum operation is used to sum all values in the channel dimension so that H x W x C feature map will become H x W. Seq_2 and seq_3 are not concatenated but instead used as separate output heads so that early layers will mimic later layers. Ground truth labels are used as extra supervision of the last layer of the encoder. More details will be introduced in our paper which will be available soon. You may print the whole model to see more details.

**Comment by heethesh** [comment]
Thanks for your reply, I used a network visualizer and it's more clear now. So the supervision for seq_2 and seq_3 heads is all classes (lanes here) combined in one channel right, as opposed to per class supervision when predicting individual probability maps and map scores?

**Comment by cardwing** [comment]
Yes.
