### ISSUE TITLE
Question about of existence ground truth of train_gt.txt 

### ISSUE THREAD

**Issue by DanLiu0623** [cardwing/Codes-for-Lane-Detection#12]
How to judge existence ground truth is '0' or '1', I refer https://github.com/XingangPan/seg_label_generate this repo but I can not understand code without any comments. So could you kindly let me know the ways to generate existence ground truth?

**Comment by cardwing** [comment]
@DanLiu0623 , there are at most four lanes in CULane. Therefore, the ground-truth labels of existence are four binary values, which indicates the existence of most left lane, left lane, right lane, most right lane, respectively. The position of lanes are given regarding the driving vehicle. "1" denotes existing while "0" denotes not existing.

**Comment by DanLiu0623** [comment]
@cardwing Thanks, Yes, I see what you said. I wonder to know how to get this four  binary values from lable.lines.txt  by code.

**Comment by cardwing** [comment]
@DanLiu0623 , please refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/11). In CULane, the binary values are already labelled and in TuSimple, I also upload the training list which contains these binary values (see the above issue). To be honest, these values are convenient to obtain by human efforts compared with using codes to automatically label them since you need to judge the position of the lanes regarding the vehicle.

**Comment by cardwing** [comment]
@DanLiu0623, you are right.

**Comment by DanLiu0623** [comment]
@cardwing Thank you for your quickly reply. But It is hard to understand the code without any comments.I also leave a message in the repo of https://github.com/XingangPan/seg_label_generate, Maybe XingangPan is too busy to reply to me.I guess you know him. Anyway, thank you very much.

**Comment by cardwing** [comment]
@DanLiu0623 I will have a quick read when free and see if I can figure the codes out. ^_^

**Comment by DanLiu0623** [comment]
@cardwing So kind of you. Thank you very much, please let me know if you have new progress. By the way, you can close this issue.
