### ISSUE TITLE
【testLane.lua】attempt to index a number value

### ISSUE THREAD

**Issue by aslily1234** [cardwing/Codes-for-Lane-Detection#120]
直接运行测试程序
`cd $ENet_ROOT
sh ./experiments/test.sh`

会提示testLane.lua 第124行 （if exist[b][i] > 0.5 then ）报错。

将其修改为 if exist[i] > 0.5 then  之后，程序可以正常运行，不太明白是什么原因，麻烦作者帮忙看下，谢谢啦！

**Comment by cardwing** [comment]
When batch size is set as 1, the model will output a probability vector which predicts the existence of lanes. The shape of this vector is just 4. Hence, you need to use 'exist[i]' instead of 'exist[b][i]' when batch size is 1 (shape of vector 'exist' is 4 when batch size is 1 and is B x 4 when batch size is B, where B is batch size and is bigger than 1).
