### ISSUE TITLE
Output:Lane Label generation from probmap

### ISSUE THREAD

**Issue by chokkarapu** [cardwing/Codes-for-Lane-Detection#13]
Hi

Im utilizing SCNN (Original) code for getting coordinates using matlab scripts.
in getLane.m files it computing the cordinates based on probmaps
the snapshot of functionality is shown below,
![image](https://user-images.githubusercontent.com/3630515/49436909-4c525800-f7e0-11e8-88ef-6b06936fff56.png)

in blue marked line, what does 580 & 288 number stand for ?
In your TensorFlow SCNN should we need to mention same numbers?

Kindly provide your inputs

**Comment by cardwing** [comment]
@chokkarapu , you can get the lane points directly from the probability maps which are generated by [test_lanenet.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py). Besides, 590 denotes the original height of the image and 288 denotes the scaled height of the image. The function of this matlab script is to "search the corresponding probmap every 20 rows for the position with the highest response. These positions are then connected by cubic splines, which are the final predictions", which is described by the paper of [SCNN](https://arxiv.org/abs/1712.06080). The tensorflow code has already taken this into consideration since the final output is set as 288 x 800.

**Comment by chokkarapu** [comment]
> @chokkarapu , you can get the lane points directly from the probability maps which are generated by [test_lanenet.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py). Besides, 590 denotes the original height of the image and 288 denotes the scaled height of the image. The function of this matlab script is to "search the corresponding probmap every 20 rows for the position with the highest response. These positions are then connected by cubic splines, which are the final predictions", which is described by the paper of [SCNN](https://arxiv.org/abs/1712.06080). The tensorflow code has already taken this into consideration since the final output is set as 288 x 800.

@cardwing  : Thanks u for information.
from "test_lanenet.py", i got probability map (instance_Seg_image) from this line:
![image](https://user-images.githubusercontent.com/3630515/49441048-6180b400-f7eb-11e8-9433-140e8dfdd449.png)

Now how we can get can get the lane points directly from the probability maps??

Kindly provide me some more insights in getting those lane points.
Thanks for your time.

**Comment by chokkarapu** [comment]
@cardwing  : Exactly I have done same thing by running main.m after generating the probability map (instance_Seg_image) from "test_lanenet.py".

In this main.m file only there are calling function getLane, in which they are utilizing those 590 & 288 numbers.
