### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fayechou** [cardwing/Codes-for-Lane-Detection#18]
![screenshot from 2018-12-11 17-44-55](https://user-images.githubusercontent.com/23359299/49791959-82f21a80-fd6c-11e8-90e7-6571f919dde9.png)
And I print the value: print (feature_list_new):
![screenshot from 2018-12-11 17-41-00](https://user-images.githubusercontent.com/23359299/49792020-aae17e00-fd6c-11e8-9756-ff532e1f4765.png)
Could you help to find out the problem? Thx~

**Comment by cardwing** [comment]
@fayechou, since you use a different input size (256 x 512 instead of 288 x 800), then the parameters of the message passing module should also be changed. Since message passing is performed in rows and columns, then you need to modify the index number from 35 to 31 in row dimension and 99 to 63 in column dimension. Just replace 35 to 31 and 99 to 63 should help. Besides, remember to modify this line `ret['prob_output'] = tf.image.resize_images(conv_output, [288, 800])`, the output size should be 256 x 512. I will remove the hard code part soon.

**Comment by cardwing** [comment]
@fayechou, you can just modify the output of the model. More specifically, modify this line `conv_output = self.conv2d(inputdata=dropout_output, out_channel=5, kernel_size=1, use_bias=True, name='conv_6')` and this line `fc_output = self.fullyconnect(relu_output, 4)` in [vgg_encoder.py](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/encoder_decoder_model/vgg_encoder.py), the output channel should be 6 (5 + 1) and the output of the fc layer should be 5. Modify other files if it raises errors related to the output dimensions.
