### ISSUE TITLE
The width of lanes?

### ISSUE THREAD

**Issue by Bonsen** [cardwing/Codes-for-Lane-Detection#261]
In https://github.com/XingangPan/seg_label_generate/blob/master/src/main.cpp (line 37), the lane width of CULane is 16 * 2 =32.
In https://xingangpan.github.io/projects/CULane.html,is is also named laneseg_label_w16.tar.gz.
It seems the width is 16 * 2 = 32?

But in https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ERFNet-CULane-PyTorch/tools/lane_evaluation/Run.sh (line 5), the lane width of CULane is 15 *2 = 30.
Do they need to be the same?

**Comment by cardwing** [comment]
`During training, the line width of the targets is set to 16 pixels,...,In order to judge whether a lane marking is successfully detected, we view lane markings as lines with widths equal to 30 pixel`. (from SCNN paper). Our evaluation code is the same as that of SCNN. They do not need to be the same. However, the lane width in training will affect the testing performance if the lane width in training is totally different from that in testing (e.g., 64 v.s. 30).

**Comment by Bonsen** [comment]
Thanks.
