### ISSUE TITLE
Issue when running the segLabelGen0.py

### ISSUE THREAD

**Issue by yoga-0125** [cardwing/Codes-for-Lane-Detection#278]
TypeError: sort() takes no positional arguments

when running the line: lanes.sort(lane_cmp). 

def lane_cmp(a, b): ......

**Comment by cardwing** [comment]
Please debug it by yourself.

**Comment by yoga-0125** [comment]
> Please debug it by yourself.

There are two parameters a & b in the definition of lane_cmp, but nothing when running lanes.sort(lane_cmp). What are a & b?

**Comment by miao02830** [comment]
Have you solved it? I have the same problem, thank you

**Comment by yoga-0125** [comment]
> Have you solved it? I have the same problem, thank you

Sorry, I didn’t solve it.

**Comment by miao02830** [comment]
okay,thankyou&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cardwing/Codes-for-Lane-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cardwing/Codes-for-Lane-Detection] Issue when running the segLabelGen0.py (#278)





  
Have you solved it? I have the same problem, thank you
  
Sorry, I didn’t solve it.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
