### ISSUE TITLE
Question about training dataset

### ISSUE THREAD

**Issue by jyang68qq** [cardwing/Codes-for-Lane-Detection#324]
Hi,
I was digging into your code recently. Nice work!

Just had question about your CULane training dataset. It seems that you didnt use txt which contains axis for lanes in the given dataset.

Could your give a little hint why this would work?

Thanks!

**Comment by cardwing** [comment]
We just use the final lane annotations to train our models. Detailed instruction can just be found in SCNN.

**Comment by akshatbhutra** [comment]
@cardwing I am interested in saving lane coordinates of each lane instance separately in a JSON file so that finally I can use this official tusimple evaluation script: https://github.com/TuSimple/tusimple-benchmark/blob/master/evaluate/lane.py but the problem is I am doing semantic segmentation, not the instance. What to do?
