### ISSUE TITLE
Questions for deployment (video inferencing)

### ISSUE THREAD

**Issue by YilmazOrkun** [cardwing/Codes-for-Lane-Detection#82]
Hello all, 

I am currently working on a solution for a deployment.
I want to feed the model with images of live camera recording.

In test_lanenet.py a list of images are inferenced at once (batch size).
As for the deployment for video inferencing, I need to grab images from a camera and have to inference them each by each.

Could you please tell me the purpose of "imgs = tf.map_fn(test_dataset.process_img, input_tensor, dtype=tf.float32) in test_lanenet.py ?

Do I need to use it for every image I grab from the camera when doing video inferencing?

Also is test_inference from LaneNet() mandatory for video inferencing?

I would be glad if you don't close this issue, as I think more questions will follow.

I will contribute/release my solution for video inferencing once finished!

**Comment by jamie0618** [comment]
tf.map_fn(test_dataset.process_img, input_tensor, dtype=tf.float32) ->
I think process_img is necessary for every image (read image / decode / resize / substract mean).

Maybe you can just use each frame form the camera as testing data (test for batch_size = 1).
You may need to modify some codes since the original code does not support batch size 1 for testing.

**Comment by zguo008** [comment]
mapfn extends the 3d tensor to 4d tensor which can then be fed into the graph. I believe this can be done by tf.expand_dims at axis=0 as well.
