### ISSUE TITLE
What changes are needed to feed an image grabbed from a camera

### ISSUE THREAD

**Issue by YilmazOrkun** [cardwing/Codes-for-Lane-Detection#87]
Dear @cardwing 

I am working on video inferencing. For that I am grabbing an image from a camera.
The image is a ndarray with dtype uint8.
Hence it will get dtype float32 after getting processed with process_img.

What changes do I have to apply in order to be able to feed the image I grab from the camera to your pretrained model?

I guess I have to change the dtype of input_tensor?
Do I have to change things in vgg_encoder.py, lanenet_merge_model.py and cnn_basenet.py?

**Comment by cardwing** [comment]
Yes. You can have a try.

**Comment by PhilippFux** [comment]
> 
> 
> Dear @cardwing
> 
> I am working on video inferencing. For that I am grabbing an image from a camera.
> The image is a ndarray with dtype uint8.
> Hence it will get dtype float32 after getting processed with process_img.
> 
> What changes do I have to apply in order to be able to feed the image I grab from the camera to your pretrained model?
> 
> I guess I have to change the dtype of input_tensor?
> Do I have to change things in vgg_encoder.py, lanenet_merge_model.py and cnn_basenet.py?

Do you find a good solution for the change?
I also want to try the Model with a Videostream. I think to change the input_tensor is not enough. Because the Session.run() Method takes a list of strings with paths. 
Do i have to change the Graph for this or is there another workaround as save the picture from the Stream into the defined Graph and change the test_img.txt file? 
Thanks for doing this nice Project.
