### ISSUE TITLE
output lane instance?

### ISSUE THREAD

**Issue by yyuuliang** [cardwing/Codes-for-Lane-Detection#88]
hi, thanks for the Tensorflow work! I have a question about the network output, in the original LaneNet, the output are binary and instance map. So I am wondering if the SCNN can also directly output the instance map. I checked the Torch SCNN, though I am not familiar with the LUA code, it seems that there is also instance map output from the network.
In the SCNN TF code, however, I only found the prob map. Is there a way to output the instance map?
So eventually I want to have a result with instance number, e.g., left 1, left 2, right 1, right 2. I have also checked Baidu Apollo code, they use SCNN and it seems that they do not use instance output from SCNN. Instead, they have a long postprocess code to get the instance. In Lanenet, the author get the instance result with the help of the instnace result map. 

Any idea about this? Thanks

The code from testlane.lua
`      line1 = outputn[{2-offset,{},{}}]
      line2 = outputn[{3-offset,{},{}}]
      line3 = outputn[{4-offset,{},{}}]
      line4 = outputn[{5-offset,{},{}}]
      lines = torch.FloatTensor(3,outputn:size(2),outputn:size(3)):fill(0)
      lines[{1,{},{}}] = line1
      lines[{2,{},{}}] = line2
      lines[{3,{},{}}] = line3
      lines[{1,{},{}}]:add(line4)
      lines[{3,{},{}}]:add(line4)`

**Comment by cardwing** [comment]
Just merge the probability maps into one map and use different numbers to represent the pixels in different lanes.

**Comment by yyuuliang** [comment]
oh the points are already grouped by different lane? let me check...

**Comment by zguo008** [comment]
@yyuuliang hi, may I know where you see the postprocessing code from the instance map?I have some trouble finding them from baidu/apollo repository. Can you share it with me? thanks a lot!

**Comment by zguo008** [comment]
@yyuuliang There output tensor has 5 dimensions with dimension 1-4 representing 4 different lanes pixel wise prob map. Using the method from the paper: search the point with the highest probility every 20 lines and connect them to get lanes. However, sometimes the output lane instance is not very accurate(see points 2 different lanes as 1 instance), so fitting a line to lane points of a same instance can cause some problem like this: the line cannot fit properly.(points of same color belongs to one instance from the output tensor)
![hw_curve55_result](https://user-images.githubusercontent.com/44756093/55601941-dfeb6380-5795-11e9-833f-a14e9079298a.jpg)
So im thinking of cluster all points again instead of using the result from the model itself.
