### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by wzd1360** [cardwing/Codes-for-Lane-Detection#99]
I'm new the whole thing, and I'm wanna ask several easy questions.
I'm wondering if the training uses CULane dataset, and the test process uses Tusimple data? And what the function of pretrained model and what's its difference from train-lanenet.py ?

Thank you in advance!

**Comment by cardwing** [comment]
The image size is different. You can naively resize the image and have a test to check if a model trained on CULane performs well in TuSimple.

**Comment by gokiri** [comment]
how can I test Tusimple dataset when your output is 4 probability maps?

**Comment by cardwing** [comment]
Just extract the coordinate of the lane points according to the instruction of TuSimple dataset.

**Comment by gokiri** [comment]
when I test tusimple data and I change the global config "__C.TRAIN.IMG_HEIGHT = 256 __C.TRAIN.IMG_WIDTH = 512",  
it comes error

"InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
Assign requires shapes of both tensors to match. lhs shape= [2560,128] rhs shape= [4500,128]
"
Q1 : do you know why?

Q2: in tusimple, input picture is 1280 x 720, so should I set the config into 1280 x 720, why you said it should be 512 x 256 in #18

**Comment by cardwing** [comment]
Q1: The trained model is for CULane and hence the input size is 288 x 800. Just train from scratch for TuSimple dataset.
Q2: The image is resized to a smaller size to save memory usage.
